name: duolingo-to-markdown

on:
  schedule:
    - cron: '1 1 * * *'  # Runs daily at 1:01 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  duolingo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Fetch Duolingo data
        uses: diegoaichele/duolingo-to-markdown@v0.2
        with:
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_PASSWORD: ${{ secrets.DUOLINGO_PASSWORD }}
          # DUOLINGO_STREAK: true  # Optional. Default is true.
          # DUOLINGO_LANGUAGE_LENGTH: 2  # Optional. Default is 2.

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated duolingo-to-markdown daily progress" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
